version: '3.7'

services:
  python-style-guide:
    image: python-style-guide
    container_name: python-style-guide
    restart: on-failure
    labels:
      - traefik.http.routers.python-style-guide.rule=Host(`python-style-guide.${BASE_DOMAIN}`)
      - traefik.http.routers.python-style-guide.entrypoints=websecure
      - traefik.http.routers.python-style-guide.service=python-style-guide
      - traefik.http.services.python-style-guide.loadbalancer.server.port=80

networks:
  default:
    external: true
    name: services
